<?php
/*
Plugin Name:  UX Qr Code Plugin
Plugin URI:   https://www.test.com 
Description:  QRCode app to let customers evaluate and rate any product. 
Version:      2.0
Author:       AhmedTaher 
Author URI:   https://www.test.com
License:      GPL2
License URI:  https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:  ux-qr
Domain Path:  /languages
*/



if ( !defined( 'ABSPATH' ) ) exit;

// Act on plugin activation
register_activation_hook( __FILE__, "activate_myplugin" );


global $ux_db_version;
$ux_db_version = '1.0';

function wpb_follow_us($content) {
    if ( is_single() ) { 

    // all Plugins directory url
    // Need to add the directory of our plugin

    $pluginUrl = plugin_dir_url('/index.html', __FILE__);

    $content .= '
            <p>
                <hr>
                <iframe src="' . $pluginUrl . 'ux-qr-plugin/index.html" frameborder="0" width="100%" height="700px"></iframe>
                <hr>
            </p>
            '
            ;
    } 
// Return the content
return $content; 
}


function ux_install() {
	global $wpdb;
	// global $ux_db_version;

	$table_name = 'Ux_Qr_Table';
	
	// $charset_collate = $wpdb->get_charset_collate();

	$sql = "CREATE TABLE $table_name (
		id mediumint(9) NOT NULL AUTO_INCREMENT,
		name text NOT NULL,
		brand text NOT NULL,
        logo MEDIUMBLOB,
		PRIMARY KEY  (id)
	)";

	require_once ABSPATH . 'wp-admin/includes/upgrade.php';
	dbDelta( $sql );

	// add_option( 'ux_db_version', $ux_db_version );
}


 
function test_plugin_setup_menu(){
    add_menu_page( 'Test Plugin Page', 'UX Plugin', 'manage_options', 'test-plugin', 'test_init' );
}
 
function test_init(){
    $ux_options_page_options = get_option( 'ux_options_page_option_name' ); // Array of All Options
    $location_0 = $ux_options_page_options['location_0']; // location
   
    $pluginUrl = plugin_dir_url('/index.html', __FILE__);

	$style = "clear: both;";
	if ($location_0 === "top left" || $location_0 === "bottom left") {
		$style = "left";
	}
	if ($location_0 === "top right" || $location_0 === "bottom right") {
		$style = "right";
	}
	if ($location_0 === "center") {
		$style = "center";
	}

    $content .= '
            <div id="pdiv" class="mcontainer" >
                <iframe class="mcontent" 
                    src="' . $pluginUrl . 'ux-qr-plugin/index.html"
                    frameborder="0"
                    ></iframe>
            </div>
			<style>
				.mcontainer {
					display: flex;
					width: 80vw;
					height: 810px;
					flex-direction: row;
					justify-content: '. $style .';
								}
				
				.mcontent {
					width: 32rem;
					height: 51rem;
								}

				/* On screens that are 600px or less, set the background color to olive */
				@media screen and (max-width: 600px) {
					.mcontainer {
						width: 95vw;
						height: 100%;
									}
					
					.mcontent {
						width: 32rem;
						height: 51rem;
									}
				</style>
            '
            ;

    echo $content;
}

add_filter('the_content', 'wpb_follow_us'); 
register_activation_hook( __FILE__, 'ux_install' );

add_action('admin_menu', 'test_plugin_setup_menu');


/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class UxOptionsPage {
	private $ux_options_page_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'ux_options_page_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'ux_options_page_page_init' ) );
	}

	public function ux_options_page_add_plugin_page() {
		add_plugins_page(
			'ux options page', // page_title
			'ux options page', // menu_title
			'manage_options', // capability
			'ux-options-page', // menu_slug
			array( $this, 'ux_options_page_create_admin_page' ) // function
		);
	}

	public function ux_options_page_create_admin_page() {
		$this->ux_options_page_options = get_option( 'ux_options_page_option_name' ); ?>

		<div class="wrap">
			<h2>ux options page</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'ux_options_page_option_group' );
					do_settings_sections( 'ux-options-page-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function ux_options_page_page_init() {
		register_setting(
			'ux_options_page_option_group', // option_group
			'ux_options_page_option_name', // option_name
			array( $this, 'ux_options_page_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'ux_options_page_setting_section', // id
			'Settings', // title
			array( $this, 'ux_options_page_section_info' ), // callback
			'ux-options-page-admin' // page
		);

		add_settings_field(
			'location_0', // id
			'location', // title
			array( $this, 'location_0_callback' ), // callback
			'ux-options-page-admin', // page
			'ux_options_page_setting_section' // section
		);
	}

	public function ux_options_page_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['location_0'] ) ) {
			$sanitary_values['location_0'] = $input['location_0'];
		}

		return $sanitary_values;
	}

	public function ux_options_page_section_info() {
		
	}

	public function location_0_callback() {
		?> <select name="ux_options_page_option_name[location_0]" id="location_0">
			<?php $selected = (isset( $this->ux_options_page_options['location_0'] ) && $this->ux_options_page_options['location_0'] === 'top right') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>top right</option>
			<?php $selected = (isset( $this->ux_options_page_options['location_0'] ) && $this->ux_options_page_options['location_0'] === 'top left') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>top left</option>
			<?php $selected = (isset( $this->ux_options_page_options['location_0'] ) && $this->ux_options_page_options['location_0'] === 'bottom right') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>bottom right</option>
			<?php $selected = (isset( $this->ux_options_page_options['location_0'] ) && $this->ux_options_page_options['location_0'] === 'bottom left') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>bottom left</option>
			<?php $selected = (isset( $this->ux_options_page_options['location_0'] ) && $this->ux_options_page_options['location_0'] === 'center') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>center</option>
		</select> <?php
	}

}
if ( is_admin() )
	$ux_options_page = new UxOptionsPage();

/* 
 * Retrieve this value with:
 * $ux_options_page_options = get_option( 'ux_options_page_option_name' ); // Array of All Options
 * $location_0 = $ux_options_page_options['location_0']; // location
 */
